#!/usr/bin/env python3
"""Generate rtl/mcm6670_cg1.hex from xtrs trs_chars.c (CG 1, standard Model I).

One-time generator, committed for reproducibility; the xtrs source file is NOT
part of this repository — fetch it from
https://github.com/TimothyPMann/xtrs/blob/master/trs_chars.c (MIT license).

What it does: parses the `CG 1` block (the standard Model I character
generator: MCM6674 datasheet data, arrows added by Tim Mann) and emits chip
rows 0..7 of all 128 glyphs verbatim. Row 0 is blank in the source data
(glyph sits in rows 1-7 of the 12-line cell: one blank line above, four
below — xtrs layout, checked against real hardware for the sibling CG 2
set). On a stock machine only 0x20-0x5F are reachable with visible output
(bit 6 = NOR(bit5, bit7), and VCLR* blanks the screen whenever the latches
are cleared); 0x00-0x1F ("odd symbols") and 0x60-0x7F are carried anyway
for structural fidelity to the 128-glyph chip.

Output format: 1024 hex bytes, address = {ascii[6:0], row[2:0]},
bit 0 = leftmost dot, bits 4:0 significant.

Usage: xtrs_font_to_hex.py path/to/trs_chars.c ../rtl/mcm6670_cg1.hex
"""

import re
import sys


def main(src_path, out_path):
    text = open(src_path, encoding="utf-8", errors="replace").read()
    # Isolate the CG 1 block: from its marker comment to the next "CG n" marker.
    start = text.index("/* CG 1 ")
    end = text.index("/* CG 2 ")
    block = text[start:end]
    entries = re.findall(r"\{\s*((?:0x[0-9a-fA-F]{2}\s*,?\s*){12})\}", block)
    if len(entries) < 128:
        sys.exit(f"expected >=128 glyph entries in CG 1, found {len(entries)}")
    lines = []
    lines.append("// mcm6670_cg1.hex — TRS-80 Model 1 character generator (Z29),")
    lines.append("// standard Tandy mask (arrows at 0x5B-0x5E instead of [ \\ ] ^).")
    lines.append("// Data: xtrs trs_chars.c CG 1 (MIT, Timothy P. Mann), itself from the")
    lines.append("// Motorola MCM6674 datasheet; arrow glyphs reconstructed by Mann.")
    lines.append("// Generated by sim/tools/xtrs_font_to_hex.py — do not edit by hand.")
    lines.append("// Layout: addr = {ascii[6:0], row[2:0]}, 8 rows/char, bit0 = left dot.")
    lines.append("// Only 0x20-0x5F are reachable with visible output on stock hardware.")
    for code in range(0x00, 0x80):
        rows = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]{2})", entries[code])]
        glyph = rows[0:8]
        if rows[0] != 0 or any(r > 0x1F for r in glyph):
            sys.exit(f"unexpected data at code {code:#04x}: {rows}")
        name = chr(code) if 0x20 <= code < 0x7F and code != 0x5C else f"<{code:#04x}>"
        lines.append(f"// {code:#04x} {name}  addr {code*8:#05x}")
        lines.append(" ".join(f"{r:02x}" for r in glyph))
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{out_path}: 128 glyphs x 8 rows written")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__.strip().splitlines()[-1])
    main(sys.argv[1], sys.argv[2])
